
default: &default
  adapter: mysql2
  encoding: utf8
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
  timeout: 5000
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: cupcake_dev
